# Generated by Django 6.0.1 on 2026-01-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text="User's biography or description", max_length=500)),
                ('avatar_url', models.URLField(blank=True, help_text="URL to the user's avatar image")),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the profile is publicly visible')),
                ('show_watched_episodes', models.BooleanField(default=True, help_text='Whether to show watched episodes on the public profile')),
                ('show_lists', models.BooleanField(default=True, help_text='Whether to show public lists on the public profile')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the profile was last updated')),
            ],
            options={
                'verbose_name': 'Public Profile',
                'verbose_name_plural': 'Public Profiles',
                'db_table': 'public_profiles',
            },
        ),
    ]
