# Generated by Django 6.0.1 on 2026-01-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_2fa_enabled',
        ),
    ]
