# Generated by Django 6.0.1 on 2026-01-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the list', max_length=255)),
                ('is_public', models.BooleanField(default=False, help_text='Whether the list is publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the list was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the list was last updated')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
                'db_table': 'lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the item was added to the list')),
                ('position', models.IntegerField(default=0, help_text='Position of the item within the list for ordering')),
            ],
            options={
                'verbose_name': 'List Item',
                'verbose_name_plural': 'List Items',
                'db_table': 'list_items',
                'ordering': ['position', '-added_at'],
            },
        ),
    ]
