# Generated by Django 6.0.1 on 2026-01-17 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(help_text='Owner of the list', on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(help_text='The list this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.list'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='media',
            field=models.ForeignKey(help_text='The media content (Movie or TVShow) in this list item', on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='media.media'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['user', 'is_public'], name='lists_user_id_2cd8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'position'], name='list_items_list_id_0a67f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('list', 'media')},
        ),
    ]
