# Generated by Django 6.0.1 on 2026-01-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('WATCHED', 'Watched')], default='PLANNED', help_text='Watch status of this item', max_length=20),
        ),
    ]
