# Generated by Django 6.0.1 on 2026-01-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_listitem_status'),
        ('media', '0004_alter_media_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('WATCHED', 'Watched')], db_index=True, default='PLANNED', help_text='Watch status of this item', max_length=20),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'status'], name='list_items_list_id_919417_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['media'], name='list_items_media_i_bffa61_idx'),
        ),
    ]
