# Generated by Django 6.0.1 on 2026-01-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(help_text='The Movie Database (TMDb) unique identifier', unique=True)),
                ('title', models.CharField(help_text='Media title', max_length=255)),
                ('original_title', models.CharField(help_text='Original title in the original language', max_length=255)),
                ('overview', models.TextField(blank=True, help_text='Media description/synopsis')),
                ('poster_path', models.CharField(blank=True, help_text='Path to the poster image', max_length=255)),
                ('backdrop_path', models.CharField(blank=True, help_text='Path to the backdrop image', max_length=255)),
                ('release_date', models.DateField(blank=True, help_text='Release date (for movies) or first air date (for TV shows)', null=True)),
                ('popularity', models.FloatField(default=0.0, help_text='TMDb popularity score')),
                ('vote_average', models.FloatField(default=0.0, help_text='Average user rating from TMDb')),
                ('vote_count', models.IntegerField(default=0, help_text='Number of votes on TMDb')),
                ('original_language', models.CharField(help_text='ISO 639-1 code of the original language', max_length=10)),
                ('media_type', models.CharField(choices=[('MOVIE', 'Movie'), ('TV_SHOW', 'TV Show')], help_text='Type of media (MOVIE or TV_SHOW)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchedEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(help_text='Season number of the episode')),
                ('episode_number', models.IntegerField(help_text='Episode number within the season')),
                ('watched_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the episode was marked as watched')),
            ],
            options={
                'verbose_name': 'Watched Episode',
                'verbose_name_plural': 'Watched Episodes',
                'db_table': 'watched_episodes',
                'ordering': ['-watched_at'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.media')),
                ('runtime', models.IntegerField(blank=True, help_text='Movie runtime in minutes', null=True)),
                ('budget', models.BigIntegerField(default=0, help_text='Movie production budget')),
                ('revenue', models.BigIntegerField(default=0, help_text='Movie revenue')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movies',
            },
            bases=('media.media',),
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.media')),
                ('number_of_seasons', models.IntegerField(default=0, help_text='Total number of seasons')),
                ('number_of_episodes', models.IntegerField(default=0, help_text='Total number of episodes')),
                ('episode_run_time', models.IntegerField(blank=True, help_text='Average episode runtime in minutes', null=True)),
                ('status', models.CharField(blank=True, help_text='Current status (Returning Series, Ended, etc.)', max_length=50)),
                ('first_air_date', models.DateField(blank=True, help_text='Date of the first episode airing', null=True)),
                ('last_air_date', models.DateField(blank=True, help_text='Date of the most recent episode airing', null=True)),
            ],
            options={
                'verbose_name': 'TV Show',
                'verbose_name_plural': 'TV Shows',
                'db_table': 'tv_shows',
            },
            bases=('media.media',),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['tmdb_id'], name='media_tmdb_id_bb03f0_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type'], name='media_media_t_9a1c04_idx'),
        ),
    ]
