# Generated by Django 6.0.1 on 2026-01-17 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedepisode',
            name='user',
            field=models.ForeignKey(help_text='User who watched the episode', on_delete=django.db.models.deletion.CASCADE, related_name='watched_episodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchedepisode',
            name='tv_show',
            field=models.ForeignKey(help_text='TV show that the episode belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='watched_episodes', to='media.tvshow'),
        ),
        migrations.AddIndex(
            model_name='watchedepisode',
            index=models.Index(fields=['user', 'tv_show'], name='watched_epi_user_id_8fd7bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchedepisode',
            unique_together={('user', 'tv_show', 'season_number', 'episode_number')},
        ),
    ]
