# Generated by Django 6.0.1 on 2026-01-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='The Movie Database (TMDb) unique identifier', null=True, unique=True),
        ),
    ]
