# Generated by Django 6.0.1 on 2026-01-18 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_tmdb_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('TV_SHOW', 'TV Show')], db_index=True, help_text='Type of media (MOVIE or TV_SHOW)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='watchedepisode',
            index=models.Index(fields=['tv_show', 'season_number', 'episode_number'], name='watched_epi_tv_show_3b59e1_idx'),
        ),
    ]
